# Generated by Django 2.2.4 on 2019-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name_str', models.CharField(max_length=256)),
                ('store_logo_img', models.ImageField(blank=True, upload_to='eatplus_chatot_app/DB/logo_img')),
                ('apply_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
