# Generated by Django 2.2.4 on 2019-08-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0002_auto_20190814_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_store_name_str', models.CharField(max_length=256)),
                ('votes', models.IntegerField(default=0)),
                ('choice_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatplus_chatbot_app.addStore')),
            ],
        ),
    ]
