# Generated by Django 2.2.4 on 2019-08-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0003_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name_str', models.CharField(help_text='최대 256자 내로 입력가능합니다.', max_length=256)),
                ('store_logo_img', models.ImageField(blank=True, upload_to='eatplus_chatot_app/DB/logo_img')),
            ],
        ),
        migrations.CreateModel(
            name='storeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('votes', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatplus_chatbot_app.store')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_store',
        ),
        migrations.DeleteModel(
            name='addStore',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
