# Generated by Django 2.2.4 on 2019-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0004_auto_20190814_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemenu',
            name='votes',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_str',
            field=models.CharField(help_text='가게 이름', max_length=256),
        ),
    ]
