# Generated by Django 2.2.4 on 2019-08-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0005_auto_20190814_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name_str',
            field=models.CharField(help_text='가게 이름', max_length=32),
        ),
    ]
