# Generated by Django 2.2.4 on 2019-08-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0006_auto_20190814_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner_name_str',
            field=models.CharField(help_text='점주 이름', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_addr_str',
            field=models.CharField(help_text='주소', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_str',
            field=models.CharField(help_text='가게 이름', max_length=32, null=True),
        ),
    ]
