# Generated by Django 2.2.4 on 2019-08-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0007_auto_20190814_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='owner_name_str',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_addr_str',
            new_name='store_addr',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_logo_img',
            new_name='store_logo',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name_str',
            new_name='store_name',
        ),
    ]
