# Generated by Django 2.2.4 on 2019-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0008_auto_20190814_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_addr',
            field=models.CharField(help_text='가게 주소', max_length=16, null=True),
        ),
    ]
