# Generated by Django 2.2.4 on 2019-08-19 06:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0009_auto_20190814_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_menu',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=1, max_length=66, size=6),
            preserve_default=False,
        ),
    ]
