# Generated by Django 2.2.4 on 2019-08-19 09:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0010_store_store_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_menu',
            field=django_mysql.models.ListCharField(models.CharField(max_length=32), max_length=198, size=6),
        ),
    ]
