# Generated by Django 2.2.4 on 2019-08-19 11:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0013_auto_20190819_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='json_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(help_text='이름', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_addr',
            field=models.CharField(help_text='주소', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(help_text='상호명', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='storeMenu',
        ),
    ]
