# Generated by Django 2.2.4 on 2019-08-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0014_auto_20190819_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(help_text='가맹주', max_length=8, null=True),
        ),
    ]
