# Generated by Django 2.2.4 on 2019-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0015_auto_20190819_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(db_column='상호', help_text='상호명', max_length=32, null=True),
        ),
    ]
