# Generated by Django 2.2.4 on 2019-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_chatbot_app', '0016_auto_20190819_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(db_column='가맹주', help_text='가맹주', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_addr',
            field=models.CharField(db_column='주소', help_text='주소', max_length=16, null=True),
        ),
    ]
