# Generated by Django 2.2.4 on 2019-08-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='상호명', max_length=255)),
                ('store_addr', models.CharField(help_text='주소', max_length=255)),
                ('owner_name', models.CharField(help_text='가맹주', max_length=32)),
                ('store_category', models.CharField(choices=[('한식', (('백반', '백반'), ('찌개', '찌개'))), ('분식', (('김밥', '김밥'),)), ('중식', (('마라탕', '마라탕'),)), ('양식', (('스테이크', '스테이크'),)), ('일식', (('덮밥', '덮밥'), ('라면', '라면'), ('초밥', '초밥'))), ('N/A', 'N/A')], default='N/A', max_length=32)),
                ('store_logo', models.ImageField(blank=True, upload_to='eatplus_chatot_app/DB/logo_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(help_text='메뉴명', max_length=255)),
                ('menu_price', models.IntegerField(help_text='가격')),
                ('image', models.ImageField(blank=True, upload_to='eatplus_chatot_app/DB/logo_img')),
                ('storeKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Store')),
            ],
        ),
    ]
