# Generated by Django 2.2.4 on 2019-08-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='storeKey',
            new_name='store',
        ),
    ]
