# Generated by Django 2.2.4 on 2019-08-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20190820_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-store']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-store_name']},
        ),
    ]
