# Generated by Django 2.2.4 on 2019-08-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20190820_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-store_name']},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='stores',
            new_name='store_name',
        ),
    ]
