# Generated by Django 2.2.4 on 2019-08-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_auto_20190820_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-store']},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='store_name',
            new_name='store',
        ),
    ]
