# Generated by Django 2.2.4 on 2019-08-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_auto_20190820_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='store_name',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Store'), help_text='상호', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(help_text='상호', max_length=255),
        ),
    ]
