# Generated by Django 2.2.4 on 2019-08-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_auto_20190821_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='store_name',
        ),
    ]
