# Generated by Django 2.2.4 on 2019-08-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_auto_20190821_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='store_name',
        ),
    ]
