# Generated by Django 2.2.4 on 2019-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_remove_menu_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_description',
            field=models.TextField(default='설명', help_text='메뉴 설명'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_description',
            field=models.TextField(default='설명', help_text='가게 설명'),
        ),
    ]
