# Generated by Django 2.2.4 on 2019-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_auto_20190822_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_discount',
            field=models.IntegerField(default=0, help_text='가격'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default='메뉴명', help_text='메뉴명', max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_price',
            field=models.IntegerField(default=0, help_text='가격'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(default='가게주', help_text='가게주', max_length=32),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_addr',
            field=models.CharField(default='주소', help_text='주소', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_description',
            field=models.TextField(default='가게 설명', help_text='가게 설명'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='상호', help_text='상호', max_length=255),
        ),
    ]
