# Generated by Django 2.2.4 on 2019-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_auto_20190822_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, upload_to='eatplus_chatot_app/DB/logo_img'),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_description',
            field=models.TextField(default='설명', help_text='메뉴 설명'),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_discount',
            field=models.IntegerField(default=0, help_text='가격'),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_name',
            field=models.CharField(default='메뉴명', help_text='메뉴명', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_price',
            field=models.IntegerField(default=0, help_text='가격'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
