# Generated by Django 2.2.4 on 2019-08-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_auto_20190823_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='menu_category',
            field=models.CharField(choices=[('점심', '점심'), ('저녁', '저녁'), ('N/A', 'N/A')], default='N/A', max_length=32),
        ),
    ]
