# Generated by Django 2.2.4 on 2019-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_store_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='menu_price',
            field=models.IntegerField(default=5500, help_text='가격'),
        ),
    ]
