# Generated by Django 2.2.4 on 2019-09-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_auto_20190823_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='menu_category',
        ),
        migrations.RemoveField(
            model_name='store',
            name='menu_description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='menu_discount',
        ),
        migrations.RemoveField(
            model_name='store',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='menu_price',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
    ]
