# Generated by Django 2.2.4 on 2019-09-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_auto_20190902_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category', max_length=32)),
                ('index', models.IntegerField(default=0, help_text='Category Index')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_addr',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_category',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_name',
        ),
        migrations.AddField(
            model_name='store',
            name='addr',
            field=models.CharField(default='Address', help_text='Address', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default='Store Dscription', help_text='Store Dscription'),
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='Store Name', help_text='Store Name', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.CharField(default='Owner', help_text='Owner', max_length=32),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sub Category', max_length=32)),
                ('index', models.IntegerField(default=0, help_text='Sub Category Index')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.Category')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_code', models.CharField(blank=True, help_text='Menu Magement Code', max_length=10, null=True)),
                ('name', models.CharField(default='Menu Name', help_text='Menu Name', max_length=255)),
                ('price', models.IntegerField(default=5500, help_text='Price')),
                ('discount', models.IntegerField(default=0, help_text='Discount')),
                ('description', models.TextField(default='Description', help_text='Description')),
                ('sales_count', models.IntegerField(default=0, help_text='Total Sales Count')),
                ('current_stock', models.IntegerField(default=0, help_text='Current Stock')),
                ('logistics_code', models.CharField(blank=True, help_text='Menu Logistics Code', max_length=10, null=True)),
                ('is_status', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='store_app.Category')),
                ('sub_categories', models.ManyToManyField(to='store_app.SubCategory')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='menus',
            field=models.ManyToManyField(to='store_app.Menu'),
        ),
    ]
