# Generated by Django 2.2.4 on 2019-09-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_auto_20190902_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_logo',
        ),
    ]
