# Generated by Django 2.2.4 on 2019-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_auto_20190902_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellingTime', models.CharField(choices=[('점심', '점심'), ('저녁', '저녁'), ('N/A', 'N/A')], default=('점심', '점심'), max_length=32)),
            ],
            options={
                'ordering': ['-sellingTime'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-category']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-category']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='sub_category',
        ),
    ]
