# Generated by Django 2.2.4 on 2019-09-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_auto_20190902_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellingTime',
        ),
        migrations.AddField(
            model_name='menu',
            name='sellingTime',
            field=models.CharField(choices=[('점심', '점심'), ('저녁', '저녁'), ('N/A', 'N/A')], default=('점심', '점심'), max_length=32),
        ),
    ]
