# Generated by Django 2.2.4 on 2019-09-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0022_auto_20190902_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sellingTime',
            field=models.CharField(choices=[('점심', '점심'), ('저녁', '저녁')], default=('점심', '점심'), max_length=32),
        ),
    ]
