# Generated by Django 2.2.4 on 2019-09-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_auto_20190902_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_management_code', models.IntegerField(default=0, help_text='Order Management Number')),
            ],
            options={
                'ordering': ['-order_management_code'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Category', max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sellingTime',
            field=models.CharField(choices=[('점심', '점심'), ('저녁', '저녁')], default=('점심', '점심'), max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(help_text='Sub Category', max_length=255),
        ),
    ]
