# Generated by Django 2.2.4 on 2019-09-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_auto_20190902_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_management_code',
            field=models.CharField(blank=True, help_text='Menu Magement Code', max_length=10, null=True),
        ),
    ]
