# Generated by Django 2.2.4 on 2019-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0027_auto_20190902_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('주문 확인중', 'Ordering'), ('주문 완료', 'Order Done'), ('픽업 준비중', 'Pickup Wait'), ('픽업 완료', 'Pickup Done'), ('주문 만료', 'Order Expire')], default=('주문 확인중', 'Ordering'), max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sellingTime',
            field=models.CharField(choices=[('점심', 'Lanch'), ('저녁', 'Dinner')], default=('점심', 'Lanch'), max_length=255),
        ),
    ]
