# Generated by Django 2.2.4 on 2019-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0028_auto_20190902_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_management_code',
            new_name='management_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('주문 확인중', '주문 확인중'), ('주문 완료', '주문 완료'), ('픽업 준비중', '픽업 준비중'), ('픽업 완료', '픽업 완료'), ('주문 만료', '주문 만료')], default=('주문 확인중', '주문 확인중'), max_length=255),
        ),
    ]
