# Generated by Django 2.2.4 on 2019-09-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_auto_20190902_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.Menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.Store'),
        ),
    ]
