# Generated by Django 2.2.4 on 2019-09-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0030_auto_20190902_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_app.Store'),
        ),
    ]
