# Generated by Django 2.2.4 on 2019-09-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0032_auto_20190903_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-index']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-index']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name',
        ),
    ]
