# Generated by Django 2.2.4 on 2019-09-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0033_auto_20190903_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sellingTime',
            field=models.CharField(choices=[('점심', 'Lunch'), ('저녁', 'Dinner')], default=('점심', 'Lunch'), max_length=255),
        ),
    ]
