# Generated by Django 2.2.4 on 2019-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0034_auto_20190903_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User Name', max_length=18)),
                ('serial', models.CharField(help_text='User S/N', max_length=18)),
                ('email', models.CharField(help_text='User ID', max_length=18)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
