# Generated by Django 2.2.4 on 2019-09-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0036_order_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='store_id',
            new_name='storeInstance',
        ),
    ]
