# Generated by Django 2.2.4 on 2019-09-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0037_auto_20190904_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.Store'),
        ),
    ]
