# Generated by Django 2.2.4 on 2019-09-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0038_order_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menu_id',
            new_name='menuInstance',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store_id',
            new_name='storeInstance',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='userInstance',
        ),
    ]
