# Generated by Django 2.2.4 on 2019-09-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0039_auto_20190904_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='logistics_code',
            field=models.CharField(blank=True, help_text='Menu Logistics Code', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='management_code',
            field=models.CharField(blank=True, help_text='Menu Magement Code', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='management_code',
            field=models.CharField(blank=True, help_text='Menu Magement Code', max_length=12, null=True),
        ),
    ]
