# Generated by Django 2.2.4 on 2019-09-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0042_auto_20190904_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sellingTime',
            field=models.CharField(choices=[(0, '점심'), (1, '저녁')], default=(0, '점심'), max_length=255),
        ),
    ]
