# Generated by Django 2.2.4 on 2019-09-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0043_auto_20190904_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, '주문 확인중'), (1, '주문 완료'), (2, '픽업 준비중'), (3, '픽업 완료'), (4, '주문 만료')], default=(0, '주문 확인중'), max_length=255),
        ),
    ]
