# Generated by Django 2.2.4 on 2019-09-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0044_auto_20190904_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sellingTime',
            field=models.CharField(choices=[('점심', '점심'), ('저녁', '저녁')], default=('점심', '점심'), max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('주문 확인중', '주문 확인중'), ('주문 완료', '주문 완료'), ('픽업 준비중', '픽업 준비중'), ('픽업 완료', '픽업 완료'), ('주문 만료', '주문 만료')], default=('주문 확인중', '주문 확인중'), max_length=255),
        ),
    ]
