# Generated by Django 2.2.4 on 2019-09-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='uniqueNumber',
            field=models.CharField(default='0000', help_text='Store Unique Number', max_length=31),
        ),
    ]
