# Generated by Django 2.2.4 on 2019-09-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_app', '0002_store_uniquenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='identifier_code',
            field=models.CharField(default='', help_text='Partner ID', max_length=255),
        ),
    ]
