# Generated by Django 2.2.4 on 2019-09-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatplus_app', '0003_auto_20190924_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='', help_text='Partner Name', max_length=255),
        ),
    ]
